---
version: "3"

services:
  web:
    build: ./docker/nginx
    container_name: web
    volumes:
      - ./:/app:ro
    ports:
      - 8000:80
  php-fpm:
    build: ./docker/php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./:/app
      - ../elu:/elu  # temporary
    expose:
      - 9000
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST}"
  composer:
    image: composer
    container_name: composer
    volumes:
      - ./:/app
      - ../elu:/elu  # temporary
    command: install
